# yaml-language-server: $schema=https://taskfile.dev/schema.json
version: "3"

tasks:
  nginx:
    desc: Deploy nginx to the cluster
    silent: true
    cmd: |
      echo "🌐 Applying ingress-nginx controller..."
      kubectl apply -f {{.APPS_DIR}}/nginx/nginx.yaml
      echo "⏳ Waiting for ingress-nginx to be ready..."
      kubectl wait --for=condition=available deployment/ingress-nginx-controller -n ingress-nginx --timeout=60s || true
      echo "✅ ingress-nginx controller is ready"

  gitea:
    desc: Deploy Gitea to the cluster
    silent: true
    cmd: |
      echo "🚀 Deploying Gitea..."
      helm upgrade --install gitea {{.APPS_DIR}}/gitea/chart \
        -n gitea \
        --create-namespace \
        -f {{.APPS_DIR}}/gitea/values.yaml
      echo "✅ Gitea deployed"

  flux:
    desc: Deploy FluxCD to the cluster
    silent: true
    cmd: |
      echo "🚀 Deploying FluxCD..."
      flux install \
        --components-extra=image-reflector-controller,image-automation-controller \
        --version=v2.5.1 \
        --toleration-keys node-role.kubernetes.io/control-plane
      
      echo "🚀 Creating SOPS secret for flux"
      kubectl create secret generic sops-age \
        --namespace=flux-system \
        --from-file=age.agekey={{.HOME_DIR}}/.config/sops/age/keys.txt \
        --dry-run=client -o yaml | kubectl apply -f -

      echo "✅ FluxCD deployed"